dist: xenial
language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '3.7'
python:
  - "3.7"
install:
  - pip3 install -r requirements.txt
script:
  - bandit --format json HelloClearShark/HelloClearSha
    rk.py
on:
    branch: dev


