notifications:
  email:
    recipients:
      - rabeyta@clearshark.com
    on_success: never # default: change
    on_failure: always # default: always

dist: xenial   # required for Python >= 3.7
language: python

python:
  - "3.7.3"

env: IMAGE_NAME="doctorruin/cs_devops_demo" IMAGE_TAG="latest"

stages:
  - test
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: python src/test_HelloClearShark.py
    - stage: test
      install: pip3 install -r requirements.txt
      script: bandit src/src.py
    - stage: build
      services: docker
      script:
      - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
      - curl -s https://ci-tools.anchore.io/inline_scan-v0.3.3 | bash -s -- -b .anchore_policy.json -f -d Dockerfile "$IMAGE_NAME:$IMAGE_TAG"
    - stage: deploy
      services: docker
      script:
      - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:$IMAGE_TAG"
      - docker push "$IMAGE_NAME:$IMAGE_TAG"


