notifications:
  email:
    recipients:
      - rabeyta@clearshark.com
    on_success: never # default: change
    on_failure: always # default: always

dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.7.3"

stages:
  - unittest
  - sectest
  - name: build
    if: branch = master

jobs:
  include:
    - stage: unittest
      script: python src/test_HelloClearShark.py
    - stage: sectest
      install: pip3 install -r requirements.txt
      script: bandit src/src.py
    - stage: build
      services: docker
      script:
      - docker build -t "${IMAGE_NAME}:latest" .
      - curl -s https://ci-tools.anchore.io/inline_scan-v0.3.3 | bash -s -- "${IMAGE_NAME}:latest"
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${IMAGE_TAG}"
      - docker push "${IMAGE_NAME}:${IMAGE_TAG}"


