dist: xenial
language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '3.7'
python:
  - "3.7"
install:
  - pip3 install bandit
script:
  - python bin/test_app.py -p $splunk_pw
on:
    branch: master


